# Generated by Django 5.2.6 on 2025-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='outcome',
            field=models.CharField(blank=True, choices=[('MERON', 'Meron'), ('WALA', 'Wala'), ('DRAW', 'Draw')], max_length=5, null=True),
        ),
    ]
