# Generated by Django 5.2.6 on 2025-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_bet_payout_amount_bet_payout_status_event_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, null=True, unique=True),
        ),
    ]
