# Generated by Django 5.2.6 on 2025-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
    ]
