# Generated by Django 5.2.6 on 2025-10-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_bet_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='betting_status',
            field=models.CharField(choices=[('STANDBY', 'Standby'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='STANDBY', max_length=10),
        ),
    ]
